<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="P04284" name="testCases.e2e.gomo.self_care.TestMyGoMo" tests="26" failures="2" timestamp="2021-09-24T15:53:27 BST" time="537.175" errors="0">
  <testcase name="testAddNewCard" time="50.841" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testFooterLinks" time="4.109" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testOrderReplacementSIM" time="0.331" classname="testCases.e2e.gomo.self_care.TestMyGoMo">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.e2e.gomo.self_care.TestMyGoMo.testOrderReplacementSIM(TestMyGoMo.java:720)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testOrderReplacementSIM -->
  <testcase name="testAccountBalanceDisplayed" time="3.362" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewUsage" time="54.550" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testEditExpiryDate" time="36.223" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewUsage" time="7.826" classname="testCases.e2e.gomo.self_care.TestMyGoMo">
    <skipped/>
  </testcase> <!-- testViewUsage -->
  <testcase name="testResetPassword" time="32.601" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testLoginToMyGoMo" time="28.713" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewOrders" time="7.890" classname="testCases.e2e.gomo.self_care.TestMyGoMo">
    <skipped/>
  </testcase> <!-- testViewOrders -->
  <testcase name="testNDDSettings" time="21.378" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewEditContactPreferences" time="54.113" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewOrders" time="15.592" classname="testCases.e2e.gomo.self_care.TestMyGoMo">
    <failure type="java.lang.AssertionError" message="expected [IN_PROGRESS] but found [COMPLETED]">
      <![CDATA[java.lang.AssertionError: expected [IN_PROGRESS] but found [COMPLETED]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testCases.e2e.gomo.self_care.TestMyGoMo.testViewOrders(TestMyGoMo.java:1585)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testViewOrders -->
  <testcase name="testNavigation" time="34.167" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testForgottenEmail" time="16.011" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testMyProfileDetailsDisplayed" time="5.149" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testViewTransactionHistory" time="6.699" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testUpdateEmail" time="20.292" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testChangeBothAddressesByEircode" time="7.703" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testRemoveCard" time="27.330" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testWebAlerts" time="14.569" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testMakePartialPayment" time="6.471" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testAccountDetailsDispay" time="7.881" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testMakeDefault" time="34.412" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testHeaderLinks" time="2.032" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
  <testcase name="testForgotPassword" time="36.930" classname="testCases.e2e.gomo.self_care.TestMyGoMo"/>
</testsuite> <!-- testCases.e2e.gomo.self_care.TestMyGoMo -->
